export type ToolResult = string;
export class ToolUnsupportedError extends Error { constructor(slug: string) { super(`This tool (${slug}) is not implemented in this browser build.`); this.name = "ToolUnsupportedError"; } }
const json = (v: unknown) => JSON.stringify(v, null, 2);
const esc = (s: string) => s.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const bytes = (s: string) => new TextEncoder().encode(s);
const hex = (b: Uint8Array) => [...b].map(x => x.toString(16).padStart(2,"0")).join("");
const b64e = (s: string) => { let bin=""; for(const b of bytes(s)) bin += String.fromCharCode(b); return btoa(bin); };
const b64d = (s: string) => { const c=s.replace(/\s/g,"").replace(/-/g,"+").replace(/_/g,"/"); if(!/^[A-Za-z0-9+/]*={0,2}$/.test(c) || c.length%4===1) throw new Error("Invalid Base64."); const bin=atob(c.padEnd(Math.ceil(c.length/4)*4,"=")); return new TextDecoder().decode(Uint8Array.from(bin,x=>x.charCodeAt(0))); };
const secure = (n:number, alphabet="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789") => { if(!Number.isInteger(n)||n<1||n>4096) throw new Error("Length must be between 1 and 4096."); const out:string[]=[]; const limit=256-Math.floor(256/alphabet.length)*alphabet.length; while(out.length<n){ const r: Uint8Array = crypto.getRandomValues(new Uint8Array(Math.max(32,n-out.length))); for(const x of r) if(x<limit && out.length<n) out.push(alphabet[x%alphabet.length]); } return out.join(""); };
const uuid=()=>crypto.randomUUID();
function parseJson(s:string){ if(!s.trim()) throw new Error("Input is empty."); try{return JSON.parse(s)}catch(e){throw new Error(e instanceof Error?e.message:"Invalid JSON.");} }
function deepSort(v:unknown):unknown { if(Array.isArray(v)) return v.map(deepSort); if(v&&typeof v==="object") return Object.fromEntries(Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,deepSort(x)])); return v; }
function words(s:string){return s.match(/[\p{L}\p{N}]+/gu)??[];}
function slug(s:string){return s.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^\p{L}\p{N}\s-]/gu,"").replace(/[\s_-]+/g,"-").replace(/^-+|-+$/g,"");}
function nums(s:string){const a=s.split(/[,\s]+/).filter(Boolean).map(Number);if(!a.length||a.some(x=>!Number.isFinite(x)))throw new Error("Enter valid numbers.");return a;}
function gcd(a:number,b:number):number{return b?gcd(b,a%b):Math.abs(a)}
function csvParse(s:string){const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'&&s[i+1]==='"'&&q){cell+='"';i++;}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell="";}else cell+=c;}row.push(cell);if(row.some(Boolean))rows.push(row);if(!rows.length)return[];const h=rows[0];return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k??`column${i+1}`,r[i]??""])))}
function csvOut(v:unknown){if(!Array.isArray(v)||!v.length||v.some(x=>!x||typeof x!=="object"||Array.isArray(x)))throw new Error("Expected a JSON array of objects.");const rs=v as Record<string,unknown>[];const ks=[...new Set(rs.flatMap(x=>Object.keys(x)))];const c=(x:unknown)=>`"${String(x??"").replaceAll('"','""')}"`;return [ks.map(c).join(","),...rs.map(r=>ks.map(k=>c(r[k])).join(","))].join("\n")}
function xml(v:unknown,tag="root"):string{if(v===null||typeof v!=="object")return `<${tag}>${esc(String(v??""))}</${tag}>`;if(Array.isArray(v))return v.map(x=>xml(x,"item")).join("");return `<${tag}>${Object.entries(v as Record<string,unknown>).map(([k,x])=>xml(x,k.replace(/[^\w-]/g,"_")||"item")).join("")}</${tag}>`}
function xmlJson(s:string){const d=new DOMParser().parseFromString(s,"application/xml");if(d.querySelector("parsererror"))throw new Error("Invalid XML.");const walk=(e:Element):unknown=>{const cs=[...e.children];if(!cs.length)return e.textContent??"";const o:Record<string,unknown>={};for(const c of cs){const v=walk(c);o[c.tagName]=c.tagName in o?(Array.isArray(o[c.tagName])?[...(o[c.tagName] as unknown[]),v]:[o[c.tagName],v]):v;}return o};return json({[d.documentElement.tagName]:walk(d.documentElement)})}
function jsonTs(v:unknown,name="Root"){const types:string[]=[];const seen=new Set<string>();const clean=(s:string)=>{const x=s.replace(/[^A-Za-z0-9]+(.)?/g,(_,c)=>c?c.toUpperCase():"")||"Root";return /^\d/.test(x)?`Type${x}`:x[0].toUpperCase()+x.slice(1)};const t=(x:unknown,h:string):string=>{if(x===null)return"null";if(Array.isArray(x))return x.length?`${t(x[0],h+"Item")}[]`:"unknown[]";if(typeof x==="object"){const n=clean(h);if(!seen.has(n)){seen.add(n);types.push(`export interface ${n} {\n${Object.entries(x as Record<string,unknown>).map(([k,y])=>`  ${/^[$A-Z_a-z][$\w]*$/.test(k)?k:JSON.stringify(k)}: ${t(y,k)};`).join("\n")}\n}`)}return n}return typeof x};t(v,name);return types.join("\n\n")||`export type ${clean(name)} = unknown;`}
function textStats(s:string){const w=words(s).length;return json({words:w,characters:[...s].length,charactersWithoutSpaces:[...s].filter(c=>!/\s/u.test(c)).length,sentences:s.trim()?s.split(/(?<=[.!?])\s+/u).filter(Boolean).length:0,lines:s? s.split(/\r?\n/).length:0,readingTimeMinutes:w?Math.max(1,Math.ceil(w/200)):0});}
function queryParse(s:string){const u=new URL(s.includes("?")?s:`https://eldevo.local/?${s.replace(/^\?/,"")}`);return json(Object.fromEntries(u.searchParams.entries()));}
function queryGen(s:string){const v=parseJson(s);if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("Expected a JSON object.");return new URLSearchParams(Object.entries(v as Record<string,unknown>).map(([k,x])=>[k,String(x)])).toString()}
function schema(s:string,type="WebPage"){const [name="",url="",description=""]=s.split(/\r?\n/);return json({"@context":"https://schema.org","@type":type,name,url,description});}
function sitemap(s:string){const urls=s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(urls.some(x=>!/^https?:\/\//i.test(x)))throw new Error("Every sitemap URL must be absolute.");return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${esc(u)}</loc></url>`).join("\n")}\n</urlset>`}
function robots(s:string){const lines=s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const host=lines.find(x=>x.startsWith("Host:"))?.slice(5).trim();const paths=lines.filter(x=>/^disallow:/i.test(x));return `User-agent: *\n${paths.length?paths.map(x=>x.replace(/^disallow:/i,"Disallow:")).join("\n"):"Disallow:"}${host?`\nHost: ${host}`:""}\nSitemap: ${lines.find(x=>/^sitemap:/i.test(x))?.split(/:\s*/,2)[1]??"https://example.com/sitemap.xml"}`}
function colorHex(s:string){const m=s.trim().replace(/^#/,'');if(!/^[0-9a-f]{3,8}$/i.test(m))throw new Error("Invalid HEX color.");const h=m.length===3?[...m].map(x=>x+x).join(""):m.slice(0,6);const n=parseInt(h,16);return `rgb(${n>>16}, ${(n>>8)&255}, ${n&255})`}
function percent(s:string){const a=nums(s);if(a.length!==2)throw new Error("Enter two numbers.");return `${(a[0]/100*a[1]).toPrecision(12).replace(/\.0+$/,'')} (${a[0]}% of ${a[1]})`}
function calculator(slug:string,s:string){const a=nums(s);switch(slug){case"percentage-calculator":return percent(s);case"percentage-change-calculator":if(a[0]===0)throw new Error("Original value cannot be zero.");return `${((a[1]-a[0])/Math.abs(a[0])*100).toFixed(4)}%`;case"ratio-calculator":if(a.length!==2||a[1]===0)throw new Error("Enter two non-zero numbers.");{const d=gcd(a[0],a[1]);return `${a[0]/d}:${a[1]/d}`};case"average-calculator":return String(a.reduce((x,y)=>x+y,0)/a.length);case"median-calculator":{a.sort((x,y)=>x-y);return String(a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2)}case"standard-deviation-calculator":{const m=a.reduce((x,y)=>x+y,0)/a.length;return String(Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/a.length))};case"discount-calculator":if(a.length!==2)throw new Error("Enter price and discount percent.");return String(a[0]*(1-a[1]/100));case"profit-margin-calculator":if(a[0]===0)throw new Error("Revenue cannot be zero.");return `${((a[0]-a[1])/a[0]*100).toFixed(4)}%`;case"markup-calculator":if(a[0]===0)throw new Error("Cost cannot be zero.");return `${((a[1]-a[0])/a[0]*100).toFixed(4)}%`;case"simple-interest-calculator":return String(a[0]*(1+a[1]*a[2]/100));case"compound-interest-calculator":return String(a[0]*(1+a[1]/100/a[3])**(a[3]*a[2]));default:throw new Error("Calculator inputs are not supported by this tool.")}}