import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use | ElDevo",
  description: "Terms and conditions governing the use of ElDevo developer tools and website.",
  alternates: {
    canonical: "https://eldevo.com/terms/",
  },
};

export default function Page() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <h1 className="text-4xl font-bold">Terms of Use</h1>

      <p className="mt-4 leading-7 text-slate-400">Last updated: August 16, 2026</p>

      <p className="mt-6 leading-7 text-slate-400">
        Welcome to ElDevo. These Terms of Use govern your access to and use of the ElDevo website,
        developer tools, converters, utilities, content, and related services.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        By accessing or using ElDevo, you agree to these Terms of Use. If you do not agree with
        these terms, please discontinue use of the website.
      </p>

      {/* 1. Description of the Service */}
      <h2 className="mt-10 text-xl font-semibold">1. Description of the Service</h2>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo provides developer-focused tools and utilities intended to help users perform common
        technical tasks, transformations, conversions, formatting operations, and other
        development-related activities.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        The tools are provided primarily for convenience and informational purposes. ElDevo does not
        guarantee that every tool will be suitable for every particular use case or technical
        environment.
      </p>

      {/* 2. Acceptable Use */}
      <h2 className="mt-10 text-xl font-semibold">2. Acceptable Use</h2>

      <p className="mt-3 leading-7 text-slate-400">
        You agree to use ElDevo only for lawful purposes and in a manner that does not interfere
        with the operation, security, or availability of the website.
      </p>

      <p className="mt-3 leading-7 text-slate-400">You must not use ElDevo to:</p>

      <ul className="mt-3 list-disc space-y-2 pl-6 leading-7 text-slate-400">
        <li>Violate applicable laws or regulations.</li>
        <li>Attempt to gain unauthorized access to systems or networks.</li>
        <li>Distribute malicious software, malware, or harmful code.</li>
        <li>Interfere with or disrupt the operation of the website.</li>
        <li>Abuse automated requests or otherwise overload the service.</li>
        <li>Attempt to bypass security or access restrictions.</li>
        <li>Use the service to facilitate unlawful activity.</li>
      </ul>

      {/* 3. Tool Output */}
      <h2 className="mt-10 text-xl font-semibold">3. Tool Output and Accuracy</h2>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo provides tools that may generate, transform, decode, format, convert, or otherwise
        process information supplied by the user.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        You are responsible for reviewing and validating all output generated by ElDevo before using
        it in production systems, applications, infrastructure, security-sensitive environments, or
        other important contexts.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo does not guarantee that generated output will always be complete, accurate,
        error-free, secure, or appropriate for your particular environment.
      </p>

      {/* 4. Sensitive Information */}
      <h2 className="mt-10 text-xl font-semibold">4. Sensitive and Confidential Information</h2>

      <p className="mt-3 leading-7 text-slate-400">
        You are responsible for determining whether information is appropriate to enter into a
        particular ElDevo tool.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        Unless you have verified how a specific tool processes information, you should avoid
        entering passwords, private keys, API keys, authentication tokens, financial information,
        personal information, proprietary source code, or other confidential data.
      </p>

      {/* 5. Availability */}
      <h2 className="mt-10 text-xl font-semibold">5. Availability and Changes</h2>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo is provided on an evolving basis. Tools, features, pages, functionality, or content
        may be added, modified, suspended, or removed at any time.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        We do not guarantee that the website or any particular tool will always be available,
        uninterrupted, secure, or free from errors.
      </p>

      {/* 6. Intellectual Property */}
      <h2 className="mt-10 text-xl font-semibold">6. Intellectual Property</h2>

      <p className="mt-3 leading-7 text-slate-400">
        Unless otherwise stated, the ElDevo website, branding, design, original content, graphics,
        code, and other materials provided by ElDevo are owned by or licensed to ElDevo and may be
        protected by applicable intellectual property laws.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        You may use the website and its tools for their intended purposes, but you may not
        reproduce, redistribute, modify, sell, or commercially exploit ElDevo content or branding
        without appropriate authorization.
      </p>

      {/* 7. User Content */}
      <h2 className="mt-10 text-xl font-semibold">7. User-Provided Information</h2>

      <p className="mt-3 leading-7 text-slate-400">
        If you voluntarily provide information through a feature of the website, you are responsible
        for ensuring that you have the necessary rights and permissions to provide that information.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        You must not submit information that you are prohibited from sharing or that violates the
        rights of another person or organization.
      </p>

      {/* 8. Third-Party Services */}
      <h2 className="mt-10 text-xl font-semibold">8. Third-Party Services and Links</h2>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo may contain links to or integrations with third-party services, websites, analytics
        providers, hosting providers, search services, advertising providers, or other external
        resources.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        Third-party services are controlled by their respective providers. ElDevo is not responsible
        for the content, availability, security, privacy practices, or policies of third-party
        websites or services.
      </p>

      {/* 9. Advertising */}
      <h2 className="mt-10 text-xl font-semibold">9. Advertising</h2>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo may display advertisements in the future through third-party advertising providers,
        including Google AdSense.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        Advertising may be subject to third-party policies, applicable laws, and user consent
        requirements. The presence of an advertisement does not constitute an endorsement or
        guarantee of the advertised product or service by ElDevo.
      </p>

      {/* 10. Disclaimer */}
      <h2 className="mt-10 text-xl font-semibold">10. Disclaimer</h2>

      <p className="mt-3 leading-7 text-slate-400">
        ElDevo and its tools are provided on an &quot;as is&quot; and &quot;as available&quot; basis
        to the extent permitted by applicable law.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        We make no warranties or representations that the website, tools, output, or content will be
        accurate, complete, reliable, secure, uninterrupted, or suitable for a particular purpose.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        You use the website and its tools at your own discretion and risk.
      </p>

      {/* 11. Limitation of Liability */}
      <h2 className="mt-10 text-xl font-semibold">11. Limitation of Liability</h2>

      <p className="mt-3 leading-7 text-slate-400">
        To the maximum extent permitted by applicable law, ElDevo and its operators shall not be
        liable for losses, damages, data loss, business interruption, security incidents, or other
        consequences arising from or related to the use of the website or its tools.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        This limitation applies to the extent permitted by applicable law and does not exclude
        liability that cannot legally be excluded.
      </p>

      {/* 12. Security */}
      <h2 className="mt-10 text-xl font-semibold">12. Security</h2>

      <p className="mt-3 leading-7 text-slate-400">
        We take reasonable measures to maintain the security and availability of ElDevo. However, no
        online service can guarantee absolute security.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        You should maintain appropriate security practices when using any online service, including
        reviewing data before submitting it and avoiding unnecessary disclosure of sensitive
        credentials.
      </p>

      {/* 13. Suspension */}
      <h2 className="mt-10 text-xl font-semibold">13. Suspension or Restriction of Access</h2>

      <p className="mt-3 leading-7 text-slate-400">
        We may restrict, suspend, or terminate access to the website or particular features when
        reasonably necessary to protect the service, users, infrastructure, or third parties, or to
        address violations of these Terms.
      </p>

      {/* 14. Changes */}
      <h2 className="mt-10 text-xl font-semibold">14. Changes to These Terms</h2>

      <p className="mt-3 leading-7 text-slate-400">
        These Terms of Use may be updated from time to time to reflect changes to ElDevo, its
        services, technology, or applicable legal requirements.
      </p>

      <p className="mt-3 leading-7 text-slate-400">
        Updated terms will be posted on this page with a revised &quot;Last updated&quot; date. Your
        continued use of ElDevo after changes are posted constitutes acceptance of the updated terms
        to the extent permitted by applicable law.
      </p>

      {/* 15. Governing Law */}
      <h2 className="mt-10 text-xl font-semibold">15. Governing Law</h2>

      <p className="mt-3 leading-7 text-slate-400">
        These Terms shall be interpreted and applied in accordance with applicable law. Where
        legally permitted, disputes relating to the website or these Terms shall be subject to the
        jurisdiction of the applicable courts.
      </p>

      {/* 16. Contact */}
      <h2 className="mt-10 text-xl font-semibold">16. Contact Us</h2>

      <p className="mt-3 leading-7 text-slate-400">
        If you have questions about these Terms of Use, please contact us through the contact
        information provided on the ElDevo website.
      </p>
    </article>
  );
}
